<a href="https://colab.research.google.com/github/FarukGirayCildir/ExamResultPrediction/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [14]:
# y = mx+b

In [15]:
df=pd.read_csv("student.csv")

In [16]:
df.head(3)

number_courses  time_study   Marks
0               3       4.508  19.202
1               4       0.096   7.734
2               4       3.133  13.811

In [17]:
y=df[["Marks"]]
x=df[["number_courses","time_study"]]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   number_courses  100 non-null    int64  
 1   time_study      100 non-null    float64
 2   Marks           100 non-null    float64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [19]:
l=LinearRegression()
model=l.fit(x,y)

In [20]:
model.predict([[4,10]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53.99164461]])

In [21]:
df['Marks'].max()

55.299

In [22]:
model.score(x,y)

0.9403656320238896

In [23]:
df.columns=['sinif','saat','puan']

In [24]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [25]:
y=df[['puan']]
x=df[['sinif','saat']]

In [26]:
lm=LinearRegression()
model=lm.fit(x,y)

In [27]:
#y=ax+b

In [28]:
model.coef_ #katsayı

array([[1.86405074, 5.39917879]])

In [29]:
model.intercept_ #sabit

array([-7.45634623])

In [30]:
model.predict([[4,5]])

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[26.99575068]])

In [31]:
(4*1.86405074)+(5*5.39917879)+(-7.45634623)

26.99575068

In [32]:
df.head(3)

sinif   saat    puan
0      3  4.508  19.202
1      4  0.096   7.734
2      4  3.133  13.811

In [33]:
s1=model.predict([[3,4.508]])[0][0]

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [34]:
(19.202-s1)/19.202

np.float64(-0.17046682485899442)

In [35]:
model.score(x,y)

0.9403656320238896